name: Deploy to PROD

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter Version, e.g. v1'
        required: true
        default: 'v1'

jobs:
  deploy:
    name: Deploy to PROD
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::group::Information"

          echo "Creating version: ${{ github.event.inputs.version }}!"
          echo "Build type is DEV ? ${{ github.ref == 'refs/heads/main' || contains(github.ref, 'feature/') }}"
          
          echo "::endgroup::"
          
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist-folder
             
      - name: Show files
        run: ls -la
         
      - name: Deploy on PROD
        uses: JamesIves/github-pages-deploy-action@3.7.1
        if: success() # && ( github.ref == 'refs/heads/prod' )
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
          TARGET_FOLDER: ${{ github.event.inputs.version }} 
          CLEAN: true # Automatically remove deleted files from the deploy branch
          COMMIT_MESSAGE: 'Deploy commit $GITHUB_SHA'
          SILENT: true
