# This is a basic workflow to help you get started with Actions

name: Build and Push to GitHub Pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, feature, prod ]
  release:
    types: 
      - created
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: |
          echo "::group::Information"

          echo "Creating version: ${{ github.event.inputs.version }}!"
          echo "Steps: ${{ toJSON(steps) }}"
          echo "Build type is DEV ? ${{ github.ref == 'refs/heads/main' || contains(github.ref, 'feature/') }}"
          
          echo "::endgroup::"
        
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Yarn Install
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: install
      
      - name: Yarn Build
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: build
 
      - name: Show files
        run: ls -la
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist-folder
          path: out
          retention-days: 5
  
  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist-folder
        
      - name: Deploy on DEV
        uses: JamesIves/github-pages-deploy-action@3.7.1
        if: success() && ( github.ref == 'refs/heads/main' || contains(github.ref, 'feature/') )
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
          TARGET_FOLDER: dev 
          CLEAN: true # Automatically remove deleted files from the deploy branch
          COMMIT_MESSAGE: 'Deploy commit $GITHUB_SHA'
          SILENT: true
         
      - name: Deploy on PROD
        uses: JamesIves/github-pages-deploy-action@3.7.1
        if: success() && ( github.ref == 'refs/heads/prod' )
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
          TARGET_FOLDER: dev 
          CLEAN: true # Automatically remove deleted files from the deploy branch
          COMMIT_MESSAGE: 'Deploy commit $GITHUB_SHA'
          SILENT: true
